### ISSUE TITLE
Error while doing docker-compose up -d

### ISSUE THREAD

**Issue by LunarstarFurry** [FachschaftMathPhysInfo/JMusicBot-docker#4]
pi@Firewalla:~/JMusicBot-docker (Lunarstar's Firewalla) $ sudo docker-compose up -d
Building musicbot_alpha
Step 1/10 : FROM maven AS build
 ---> ed92de59a7d8
Step 2/10 : WORKDIR /MusicBot
 ---> Using cache
 ---> d0685b74df83
Step 3/10 : COPY . .
 ---> Using cache
 ---> 8562f3a388ac
Step 4/10 : RUN sed "s%<version>Snapshot</version>%<version>0.3.8</version>%g" pom.xml -i &&     mvn package
 ---> Running in 1cf4e25268ff
[INFO] Scanning for projects...
[INFO] 
[INFO] -----------------------< com.jagrosh:JMusicBot >------------------------
[INFO] Building JMusicBot 0.3.8
[INFO] --------------------------------[ jar ]---------------------------------
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-resources-plugin/2.6/maven-resources-plugin-2.6.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  21.198 s
[INFO] Finished at: 2022-04-29T03:05:29Z
[INFO] ------------------------------------------------------------------------
[ERROR] Plugin org.apache.maven.plugins:maven-resources-plugin:2.6 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-resources-plugin:jar:2.6: Could not transfer artifact org.apache.maven.plugins:maven-resources-plugin:pom:2.6 from/to central (https://repo.maven.apache.org/maven2): transfer failed for https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-resources-plugin/2.6/maven-resources-plugin-2.6.pom: Unknown host repo.maven.apache.org: Temporary failure in name resolution -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException
ERROR: Service 'musicbot_alpha' failed to build: The command '/bin/sh -c sed "s%<version>Snapshot</version>%<version>0.3.8</version>%g" pom.xml -i &&     mvn package' returned a non-zero code: 1

Am I doing something wrong lmao

**Comment by christian-heusel** [comment]
Hey there, to it looks like the actual error is the following one:

> Unknown host repo.maven.apache.org: Temporary failure in name resolution

So the error is most-likely not related to the build here itself! Does DNS work on your Pi in general? 😄 🌐

**Comment by LunarstarPony** [comment]
Well, I'm trying to run it on my Firewalla Purple which I use as a router so It should have working internet?

**Comment by LunarstarPony** [comment]
https://firewalla.com/products/firewalla-purple
I'm trying to run it on this

**Comment by LunarstarPony** [comment]
Step 4/10 : RUN sed "s%<version>Snapshot</version>%<version>0.3.8</version>%g" pom.xml -i &&     mvn package
 ---> Running in efb7fd73c9a2
[INFO] Scanning for projects...
[INFO] 
[INFO] -----------------------< com.jagrosh:JMusicBot >------------------------
[INFO] Building JMusicBot 0.3.8
[INFO] --------------------------------[ jar ]---------------------------------
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-resources-plugin/2.6/maven-resources-plugin-2.6.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  21.468 s
[INFO] Finished at: 2022-04-29T10:54:23Z
[INFO] ------------------------------------------------------------------------
[ERROR] Plugin org.apache.maven.plugins:maven-resources-plugin:2.6 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-resources-plugin:jar:2.6: Could not transfer artifact org.apache.maven.plugins:maven-resources-plugin:pom:2.6 from/to central (https://repo.maven.apache.org/maven2): transfer failed for https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-resources-plugin/2.6/maven-resources-plugin-2.6.pom: Unknown host repo.maven.apache.org: Temporary failure in name resolution -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException
ERROR: Service 'musicbot_alpha' failed to build: The command '/bin/sh -c sed "s%<version>Snapshot</version>%<version>0.3.8</version>%g" pom.xml -i &&     mvn package' returned a non-zero code: 1
pi@Firewalla:~/JMusicBot-docker (Lunarstar's Firewalla) $ wget https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-resources-plugin/2.6/maven-resources-plugin-2.6.pom
--2022-04-29 18:54:34--  https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-resources-plugin/2.6/maven-resources-plugin-2.6.pom
Resolving repo.maven.apache.org (repo.maven.apache.org)... 199.232.192.215, 199.232.196.215
Connecting to repo.maven.apache.org (repo.maven.apache.org)|199.232.192.215|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 8115 (7.9K) [text/xml]
Saving to: 'maven-resources-plugin-2.6.pom'

maven-resources-plugin-2.6.pom                               100%[===========================================================================================================================================>]   7.92K  --.-KB/s    in 0.004s  

2022-04-29 18:54:35 (2.04 MB/s) - 'maven-resources-plugin-2.6.pom' saved [8115/8115]

pi@Firewalla:~/JMusicBot-docker (Lunarstar's Firewalla) $ 

I tried to download the thing using wget which does seems to be working tho

**Comment by christian-heusel** [comment]
Alright, then it is probably a problem of having working DNS inside of docker
Maybe sth like this helps? https://serverfault.com/questions/642981/docker-containers-cant-resolve-dns-on-ubuntu-14-04-desktop-host
But this is definitely not an error of this particular docker-compose project!

**Comment by christian-heusel** [comment]
@LunarstarPony were you able to fix the problem?

**Comment by LunarstarPony** [comment]
rn Not really, but I do confirm that's just the issue with my Firewalla tho, tried it with Kali Linux and it works fine there
